name: Check all websites

on:
  schedule:
    - cron:  '13 5-21 * * *' # runs every hour xx:13, between 5 and 21 (UTC)
  workflow_dispatch:

jobs:
  check_all_websites:
    uses: metaodi/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/all.csv
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

