name: Check all websites

on:
  schedule:
    - cron:  '5 9 * * 3' # runs every Wednesday at 9:05 UTC 
  workflow_dispatch:
    inputs:
      notifications:
          description: 'True to send notifications'
          required: true
          default: true
          type: boolean
      commit:
          description: 'True to commit hashes'
          required: true
          default: true
          type: boolean

jobs:
  check_aubonne_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/aubonne.csv
      keywords-path: keywords/aubonne.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_dietlikon_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/dietlikon.csv
      keywords-path: keywords/dietlikon.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_grancia_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/grancia.csv
      keywords-path: keywords/grancia.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_itingen_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/itingen.csv
      keywords-path: keywords/itingen.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_lyssach_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/lyssach.csv
      keywords-path: keywords/lyssach.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_pratteln_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/pratteln.csv
      keywords-path: keywords/pratteln.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_riddes_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/riddes.csv
      keywords-path: keywords/riddes.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_rothenburg_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/rothenburg.csv
      keywords-path: keywords/rothenburg.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_spreitenbach_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/spreitenbach.csv
      keywords-path: keywords/spreitenbach.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_st_gallen_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/st_gallen.csv
      keywords-path: keywords/st_gallen.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_vernier_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/vernier.csv
      keywords-path: keywords/vernier.txt
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

