name: Check all websites

on:
  schedule:
    - cron:  '5 9 * * 3' # runs every Wednesday at 9:05 UTC 
  workflow_dispatch:
    inputs:
      notifications:
          description: 'True to send notifications'
          required: true
          default: true
          type: boolean
      commit:
          description: 'True to commit hashes'
          required: true
          default: true
          type: boolean

jobs:
  check_all_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/all.csv
      send-notifications: ${{ !contains(inputs.notifications, 'false') }}
      commit-hashes: ${{ !contains(inputs.commit, 'false') }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

