name: Check all websites

on:
  schedule:
    - cron:  '5 2/12 * * *' # runs twice a day, at 02:05 and 14:05 UTC
  workflow_dispatch:
    inputs:
      notifications:
          description: 'True to send notifications'
          required: true
          default: true
          type: boolean

jobs:
  check_all_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/all.csv
      send-notifications: ${{ inputs.notifications }} 
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

