name: Check websites for changes

on:
  workflow_call:
    inputs:
      csv-path:
        description: 'Path to a CSV containing the URLs'
        required: true
        type: string
      keywords-path:
        description: 'Path to a TXT containing the keywords'
        required: true
        type: string
      send-notifications:
        description: 'Run this workflow with notifications'
        default: true
        required: false
        type: boolean
    secrets:
      MS_TEAMS_WEBHOOK_URL:
        required: true
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install sqlite3

      - id: set-matrix
        env:
           CSV_PATH: ${{ inputs.csv-path }}
        run: |
          matrix=$(./workflow/matrix.sh $CSV_PATH | jq -c '.')
          echo $matrix
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  notify:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix: ${{fromJSON(needs.build-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install sqlite3
          if [ "${{ matrix.type }}" = "dynamic" ] ; then
                sudo apt-get update
                sudo apt-get install chromium-browser
          fi
      
      - name: Check website
        id: website
        run: |
          echo "URL: ${{ matrix.url }}, selector: ${{ matrix.selector }}"
          mkdir text
          mkdir new_hashes
          matches=$(./lib/website_hash.py -u "${{ matrix.url }}" -f "hashes/${{ matrix.slug }}.txt" -k "${{ inputs.keywords-path }}" -n "new_hashes/${{ matrix.slug }}.txt" -s "${{ matrix.selector }}" -t "${{ matrix.type }}" -o text/${{ matrix.slug }}.txt --verbose)
          echo $matches
          {
            echo 'matches<<EOF'
            echo $matches | cut -c 1-2000
            echo EOF
          } >> "$GITHUB_OUTPUT"
          if [[ -n "$matches" ]] ; then
            echo "has_matches=1" >> $GITHUB_OUTPUT
          fi
          
      - name: Were there any matches?
        run: |
          echo "Matches: ${{ steps.website.outputs.has_matches }}"

      - name: Notify about website changes
        if: ${{ steps.website.outputs.has_matches && inputs.send-notifications }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: "🟢 Webseite «${{matrix.label }}» hat Änderungen"
          summary: "Webseite «${{matrix.label }}» hat Änderungen"
          text: "[${{matrix.label }}](${{ matrix.url }}): ${{ steps.website.outputs.matches }}"
          theme_color: 3AB660
          actions: '[{ "@type": "OpenUri", "name": "Webseite anschauen", "targets": [{ "os": "default", "uri": "${{ matrix.url }}" }] }, { "@type": "OpenUri", "name": "Logs anschauen", "targets": [{ "os": "default", "uri": "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }]'
            
      - name: Note error for later
        if: ${{ failure() }}
        run: |
          mkdir error_counts
          touch error_counts/${{ matrix.slug }}.txt
      
      - name: Notify about failure
        if: ${{ failure()  && matrix.error_count > 0 && inputs.send-notifications }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: "🔴 Website-Check für «${{ matrix.label }}» fehlgeschlagen"
          summary: GitHub Action fehlgeschlagen für «${{ matrix.label }}»
          theme_color: CC0000
          actions: '[{ "@type": "OpenUri", "name": "Logs anschauen", "targets": [{ "os": "default", "uri": "https://github.com/ebp-group/website-keyword-monitor/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }]'
            
      
      - name: Upload hash as artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: output
          path: |
            new_hashes
            text
            error_counts
