name: Manual check of websites

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
      notifications:
          description: 'True to send notifications'
          required: true
          default: false
          type: boolean
      commit:
          description: 'True to commit hashes'
          required: true
          default: false
          type: boolean

jobs:
  check_aubonne_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/aubonne.csv
      keywords-path: keywords/aubonne.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_dietlikon_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/dietlikon.csv
      keywords-path: keywords/dietlikon.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_grancia_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/grancia.csv
      keywords-path: keywords/grancia.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_itingen_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/itingen.csv
      keywords-path: keywords/itingen.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  check_lyssach_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/lyssach.csv
      keywords-path: keywords/lyssach.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_pratteln_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/pratteln.csv
      keywords-path: keywords/pratteln.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_riddes_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/riddes.csv
      keywords-path: keywords/riddes.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_rothenburg_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/rothenburg.csv
      keywords-path: keywords/rothenburg.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_spreitenbach_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/spreitenbach.csv
      keywords-path: keywords/spreitenbach.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_st_gallen_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/st_gallen.csv
      keywords-path: keywords/st_gallen.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

  check_vernier_websites:
    uses: ebp-group/website-keyword-monitor/.github/workflows/check_websites.yml@main
    with:
      csv-path: csv/vernier.csv
      keywords-path: keywords/vernier.txt
      send-notifications: ${{ inputs.notifications }}
      commit-error-count: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
      
  update_hashes:
    needs:
      - check_aubonne_websites
      - check_dietlikon_websites
      - check_grancia_websites
      - check_itingen_websites
      - check_lyssach_websites
      - check_pratteln_websites
      - check_riddes_websites
      - check_rothenburg_websites
      - check_spreitenbach_websites
      - check_st_gallen_websites
      - check_vernier_websites
    uses: ebp-group/website-keyword-monitor/.github/workflows/update_hashes.yml@main
    with:
      send-notifications: ${{ inputs.notifications }}
      commit-hashes: ${{ inputs.commit }}
    secrets:
      MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}

